# -*- coding: utf-8 -*-
"""ExercicioAPIFinance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Km_-bymYuv2EffpKbQo-eDsTk9HvYrC
"""

import requests

URL = 'https://api.hgbrasil.com/finance?key=02c3ebfb'
resposta = requests.get(URL)
dolar = resposta.json()['results']['currencies']['USD']['buy']
euro = resposta.json()['results']['currencies']['EUR']['buy']

real = float(input('Digite um valor em real:'))
usd_dolar = real/dolar
eur_euro = real/euro
print(f'Dolar: {usd_dolar:.2f} \n Euro: {eur_euro:.2f}')